#!/bin/sh

# Build client production
npm run client:build:prod
# add git build
git add client/build/

# Run Tests
# echo "*****Running unit tests******"

# Stash the working directory changes before running the unit tests, and unstash back. 
# This makes sure, we're running the tests only in the clean working directory.
# https://dev.to/akdevcraft/git-pre-hook-pre-commit-hook-with-npm-project-44p2

# stash_commit="$(git stash create)"
# git reset —-hard
# npm test -- --watchAll=false
# status=$?
# if [[ -n "${stash_commit}" ]]
#  then git stash apply "${stash_commit}"
# fi
# exit $status
